# -*- coding: utf-8 -*-
"""crop_recommendation (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8xWvCBi_zURUqkyNJbsvTH3TIqivIYL
"""

import pandas as pd
import numpy as np
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier, StackingClassifier

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('crop_recommendation_final.csv')

df

df.head()

df['label'].value_counts()

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

df = df.drop_duplicates()
df = df.dropna()
df.columns = df.columns.str.strip()

print("\nUnique crops:", df['label'].unique())

crop_encoder = LabelEncoder()

df['crop_encoded'] = crop_encoder.fit_transform(df['label'])

print("\nCrop encoding:")
for i, c in enumerate(crop_encoder.classes_):
    print(f"  {i} = {c}")

feature_cols = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']

X = df[feature_cols]
y = df['crop_encoded']

print(f"\nFeatures: {feature_cols}")
print(f"X shape: {X.shape}")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled = pd.DataFrame(X_train_scaled, columns=feature_cols)
X_test_scaled=scaler.transform(X_test)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=feature_cols)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy: {acc * 100:.2f}%")

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)



param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestClassifier(random_state=42)

crop_model = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)

crop_model.fit(X_scaled_df, y)

y_pred_crop = crop_model.predict(X_test)
crop_acc = accuracy_score(y_test, y_pred_crop)
print(f"\nModel Accuracy: {crop_acc * 100:.2f}%")

print(crop_model.best_score_)

best_model = crop_model.best_estimator_

print("Best Params:", crop_model.best_params_)
print("CV Accuracy:", crop_model.best_score_ * 100)

best_n = crop_model.best_params_['n_estimators']
print("Best n_estimators:", best_n)

with open('crop_model.pkl', 'wb') as f:
    pickle.dump(crop_model, f)







skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

model_cr = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=skf,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)
model_cr.fit(X_train, y_train)

y_pred_sk = model_cr.predict(X_test)
acc_sk = accuracy_score(y_test, y_pred_sk)
print(f"\nModel Accuracy: {acc_sk * 100:.2f}%")

with open('model_cr.pkl', 'wb') as f:
    pickle.dump(model_cr, f)







param_grid = {
    'n_estimators': [100, 150, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestClassifier(random_state=42)

cr_model = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

cr_model.fit(X_train_scaled, y_train)

y_pred_ = cr_model.predict(X_test_scaled)
accu = accuracy_score(y_test, y_pred_)
print(f"\nModel Accuracy: {accu * 100:.2f}%")

with open('cr_model.pkl', 'wb') as f:
    pickle.dump(cr_model, f)





sample = pd.DataFrame(
    [[90, 42, 43, 20.8, 82.0, 6.5, 202.9]],
    columns=feature_cols
)
sample_scaled = pd.DataFrame(scaler.transform(sample), columns=feature_cols)

crop_id = crop_model.predict(sample_scaled)
crop_name = crop_encoder.inverse_transform(crop_id)[0]



with open('model.pkl', 'wb') as f:
    pickle.dump(crop_model, f)
print("✅ Saved: crop_model.pkl")

with open('scaler_crop.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print("✅ Saved: scaler_crop.pkl")

with open('crop_encoder.pkl', 'wb') as f:
    pickle.dump(crop_encoder, f)
print("✅ Saved: crop_encoder.pkl")

print("  - crop_model.pkl")
print("  - scaler_crop.pkl")
print("  - crop_encoder.pkl")

with open('model.pkl', 'wb') as f:
    pickle.dump(crop_model, f)

with open('model_4.pkl', 'wb') as f:
    pickle.dump(cr_model, f)

print(df.shape)
print(df['label'].nunique())
print(df['label'].value_counts())

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(data=df, x='label', y='temperature')
plt.xticks(rotation=90)
plt.show()

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

print("XGBoost Accuracy:", accuracy_score(y_test, y_pred_xgb) * 100)

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1]
}

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)



grid = GridSearchCV(
    XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'),
    param_grid,
    cv=skf,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)

grid.fit(X_train, y_train)

best_xgb = grid.best_estimator_

xgb_y_pred = best_xgb.predict(X_test)

print("Best Params:", grid.best_params_)
print("XGBoost Accuracy:", accuracy_score(y_test, xgb_y_pred) * 100)

with open('xgb_model.pkl', 'wb') as f:
    pickle.dump(xgb_model, f)

with open('xgb_grid_model.pkl', 'wb') as f:
    pickle.dump(grid, f)

dt_model = DecisionTreeClassifier(max_depth=5, random_state=42)

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)

voting_model= VotingClassifier(
    estimators=[
        ('dt', dt_model),
        ('rf', rf_model),
        ('xgb', xgb_model)
    ]
)

voting_model.fit(X_train, y_train)

y_pred = voting_model_soft.predict(X_test)

print("Soft Voting Accuracy:", accuracy_score(y_test, y_pred) * 100)

precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

print(classification_report(y_test, y_pred))

